### ISSUE TITLE
Open Quick Links in new tab 

### ISSUE THREAD

**Issue by zidanekarim** [stuysu/today.stuysu.org#1]
Currently when you click on a button in the Quick Links section it opens in the same tab as today.stuysu.org. I believe this to be inefficient, and might take away from students who are still using the website for other purposes.

 It's not a huge deal as they can just press back but it is a bit annoying. Would be nice to open in a new tab

**Comment by thunder-red-star** [comment]
+1.

**Comment by willowiscool** [comment]
Thanks for raising this issue and commenting. Sorry I missed it for so long. If you have another issue in the future and nobody responds for a while on github, feel free to email it@stuysu.org (or talk to anyone on the IT team in person, if you can find us)
